name: Linters and Tests

on: pull_request

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Rubocop Report
        run: bundle exec rubocop --color

  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
        env:
          TELEGRAM_TOKEN: fake_token_for_tests
          DOG_API_KEY: ''
          CAT_API_KEY: ''